### ISSUE TITLE
Release version 0.1.0

### ISSUE THREAD

**Issue by jamesmunns** [japaric/serde-json-core#10]
It looks like the release of this crate is blocked by @japaric not having crate ownership/permissions to the [`serde-json-core`](https://crates.io/crates/serde-json-core/) crate.

@dtolnay could you please grant Jorge permissions to the repo on crates.io so this can be released?

EDIT: Or alternatively, could you (dtolnay) please publish the current version of the crate? Though that would leave this crate in a similar version in the future.

**Comment by dtolnay** [comment]
I added him as owner when I uploaded 0.0.1. It should be in his pending invites:
https://crates.io/me/pending-invites

**Comment by keithduncan** [comment]
I was able to work around this with a `[patch]` in my manifest to get this compiling on stable for the time being:

```
[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-json-core = "0.0.1"

[patch.crates-io]
serde-json-core = { git = "https://github.com/japaric/serde-json-core" }
```

**Comment by thejpster** [comment]
Just a +1 as I fell over this one today. Thanks @keithduncan for the work-around.

**Comment by jamesmunns** [comment]
Heu @japaric, would it be possible to release this?

**Comment by japaric** [comment]
Done. https://crates.io/crates/serde-json-core/0.1.0
