### ISSUE TITLE
Bump dependencies

### ISSUE THREAD

**Issue by Pzixel** [japaric/serde-json-core#5]
Crate is currently working with heapless v0.2.4 and serde_derive v1.0.33. I think versions should be bumped, because these versions contains different bugs and so on. Unfortunately, changes in `heapless` was too big so I'm just not able to figure out how they should be fixed.

**Comment by gbip** [comment]
Take a look at this pr #7.

**Comment by jamesmunns** [comment]
Also relevant: #10

**Comment by japaric** [comment]
Done in #20
